apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opti-nms.fullname" . }}-backup-pvc
  labels:
    {{- include "opti-nms.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.storageSize | default "5Gi" }}
