{{- if or (eq .Values.secrets.MONGO_PASSWORD "") (eq .Values.secrets.ENCRYPTION_SECRET "") (eq .Values.secrets.JWT_SECRET "") (eq .Values.secrets.APP_MASTER_TOKEN "") }}
{{- fail "MONGO_PASSWORD, ENCRYPTION_SECRET, JWT_SECRET and APP_MASTER_TOKEN must be set in values or --set" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opti-nms.fullname" . }}-secret
  labels:
    {{- include "opti-nms.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
